version: '3.8'

services:
  artist:
    build: .
    container_name: Artist
    ports:
      - "5001:5000"
    volumes:
      - /mnt/user/appdata/artist/data:/app/data
    restart: unless-stopped
    labels:
      - "com.unraid.container.name=Artist Tour Tracker"
      - "com.unraid.container.icon=https://raw.githubusercontent.com/e-fied/artist/main/icon.png"
      - "com.unraid.container.description=Artist Tour Tracker application"
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=false"
      - "com.centurylinklabs.watchtower.schedule=0 0 * * * *" 

      